### ISSUE TITLE
Incorrect test

### ISSUE THREAD

**Issue by gregsdennis** [jsonpath-standard/jsonpath-compliance-test-suite#3]
I think `union array slice, negative range with default step` is incorrect.

```json
{
  "name": "union array slice, negative range with default step",
  "selector": "$[-1:-3]",
  "document": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9
  ],
  "result": []
}
```

I think the expected result should be `[9]`.  The slice `-1:-3` should start at the last index, take it, and increment by one (which takes it out of the bounds of the array, stopping selection).

**Comment by glyn** [comment]
Let's follow through the detailed semantics section of the 21 April 2021 version of the [array selector semantics](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-detailed-semantics).

The default step value is `1`. Then:
```
Normalize(-1, 10) = 9
Normalize(-3, 10) = 7
Bounds(-1, -3, 1, 10) = Bounds(9, 7, 1, 10) = (MIN(MAX(9, 0), 10), MIN(MAX(7, 0), 10)) = (9, 7)
```

Plugging `(lower, upper) = (9, 7)` into the indexing pseudocode:
```
IF step > 0 THEN

  i = lower
  WHILE i < upper:
    SELECT a(i)
    i = i + step
  END WHILE

ELSE if step < 0 THEN

  i = upper
  WHILE lower < i:
    SELECT a(i)
    i = i + step
  END WHILE

END IF
```
gives:
```
 i = 9
  WHILE i < 7:
    SELECT a(i)
    i = i + 1
  END WHILE
```
which selects no elements since the `WHILE` loop terminates immediately (because `9 < 7` is false).

Thus the expected result `[]` is correct.

**Comment by gregsdennis** [comment]
🤔 That algorithm seems a bit more efficient than what I cobbled together.  I'll try that and report back.

**Comment by glyn** [comment]
If you don't mind reading Rust, there's also the Reference Implementation to compare notes with. The Python-like array slicing was split out into its own crate: [slyce](https://github.com/mkmik/slyce).

**Comment by gregsdennis** [comment]
That algorithm helped.  I had to do some gymnastics around null values for when slice components were missing, but I got it.  Thanks.
