### ISSUE TITLE
Multiple selectors including wildcard-selector and filter-selector

### ISSUE THREAD

**Issue by jg-rp** [jsonpath-standard/jsonpath-compliance-test-suite#45]
If I've understood the spec correctly (that's a big "if"), bracketed-selection can include wildcard and filter selectors, potentially producing duplicate nodes.

```plain
selector            = name-selector  /
                      wildcard-selector /
                      slice-selector /
                      index-selector /
                      filter-selector

bracketed-selection = "[" S selector *(S "," S selector) S "]"
```

For example, these would be valid queries.

```plain
$.store.book[*, 0, 1, 1:3]
$.store.book[*, *, *]
$.store.book[?@.isbn, 1, 2, 3, *]
```

I don't believe this is covered by the test suite yet.

**Comment by gregsdennis** [comment]
Yes, those are all valid (you read correctly), and we've had a lot of discussion about it.  Ultimately, it came down to allowing it even though it doesn't make sense for a user to do so because there could be unintentional overlap between selectors.

We probably don't have _duplicate_ selector tests, but I'm pretty sure we have overlapping selector tests.

**Comment by gregsdennis** [comment]
Others to be sure to include are things like `$.store.book[ 1, ?.author=='Jane', 3:5]` (note the comparative expression).
